# Generated by Django 5.2.3 on 2025-06-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebusinesshour',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterUniqueTogether(
            name='storestatus',
            unique_together={('store', 'timestamp_utc')},
        ),
    ]
