# Generated by Django 5.2.3 on 2025-06-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_monitor', '0002_alter_storebusinesshour_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storestatus',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='storestatus',
            constraint=models.UniqueConstraint(fields=('store', 'timestamp_utc'), name='store_timestamp_pk'),
        ),
    ]
