# Generated by Django 5.2.3 on 2025-06-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_monitor', '0003_alter_storestatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestatus',
            name='status',
            field=models.TextField(),
        ),
    ]
