# Generated by Django 5.2.3 on 2025-06-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store_monitor", "0004_alter_storestatus_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storestatus",
            options={"managed": False, "ordering": ["timestamp_utc"]},
        ),
    ]
