# Generated by Django 5.2.3 on 2025-06-15 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_monitor", "0005_alter_storestatus_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp_utc", models.DateTimeField(auto_now_add=True)),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("status", models.CharField(default="pending", max_length=100)),
            ],
        ),
    ]
